Update to SI, SA Milestones
*Spring Integration 4.0.0.M3
*Spring AMQP 1.3.0.M2

Note: SI now includes `spring-integration-mqtt`

Also fix a race condition in JobCommandTests.testStopJobExecution:

org.junit.ComparisonFailure: expected:<STOPP[ED]> but was:<STOPP[ING]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.springframework.xd.shell.command.JobCommandTests.testStopJobExecution(JobCommandTests.java:433)

Polishing - PR Comment

Fix loop waiting for job to stop.