Update to SPR, SI, SA Snapshots
*Spring 4.0.1
*Spring Integration 4.0.0
*Spring AMQP 1.3.0

Note: SI now includes `spring-integration-mqtt`

Also fix a race condition in JobCommandTests.testStopJobExecution:

org.junit.ComparisonFailure: expected:<STOPP[ED]> but was:<STOPP[ING]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.springframework.xd.shell.command.JobCommandTests.testStopJobExecution(JobCommandTests.java:433)